[package]
name = "tracing-gcp-formatter"
version = "0.8.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "A Rust library for GCP structured logging"
repository = "https://github.com/worldline/gcp-structured-log"

[features]
default = ["hostname"]
hostname =  ["gethostname"]

[dependencies]
chrono.workspace = true
gethostname = { version = "1.1.0", optional = true }
serde.workspace = true
serde_json.workspace = true
tracing = { version = "0.1.44", default-features = false, features = ["log", "std", "attributes"] }
tracing-subscriber = { version = "0.3.23", default-features = false, features = ["registry", "fmt"] }
