[workspace]
members = ["crates/gcp-log", "crates/models", "crates/tracing-gcp-formatter"]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2024"
authors = ["Philippe Vlérick <philippe.vlerick@worldline.com>"]
license = "MIT"

[workspace.dependencies]
chrono = { version = "0.4.44", default-features = false, features = ["serde", "clock"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
