[package]
name = "gcp-log"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "A CLI tool for structured logging on GCP"
repository = "https://github.com/yourusername/gcp-log"

[dependencies]
anyhow = "1.0.102"
serde_json.workspace = true
chrono.workspace = true
log-entry = { path = "../log-entry" }
clap = { version = "4.6.1", features = ["derive"] }
colored = "3.1.1"

[[bin]]
name = "gcp-log"
path = "src/main.rs"
